### ISSUE TITLE
Práctica de Gestión de Riesgos

### ISSUE THREAD

**Issue by Anthony4523** [SistemasTecTlaxiaco/practica-planificacion-de-recursos-entrevista-EGAL#1]
[PRÁCTICA_GESTIÓN DE LOS RIESGOS.pdf](https://github.com/SistemasTecTlaxiaco/practica-planificacion-de-recursos-entrevista-EGAL/files/7558653/PRACTICA_GESTION.DE.LOS.RIESGOS.pdf)

**Comment by Anna-Aparicio** [comment]
Calificación 20 puntos

**Comment by josealfredo79** [comment]
Bien hecho y revisado
